### PR TITLE
new var and const definitions, preliminary esp32 support

### PR DESCRIPTION
**Pull request by martin-ac100**
new 'var' and 'const' definitions, the old 'var' did not work?

esp32 support in very early stage - no peripherals yet

### CODE REVIEW

**Comment by zevv** [comment]
Thanks. I'd like to merge the var and const, but I'm not yet sure about pulling in the esp32 arch - this might end up growing a big library of forth wrappers around idf.py, which probably would deserve a repository of its own instead of being part of the core zforth.

**Comment by martin-ac100** [comment]
You are right. I should mind the KISS rule - keep it stupid simple. Don't merge ESP32.

**Comment by martin-ac100** [comment]
I added a **'see'** word for decompilation. It works different from other Forth's see while I can't parse next word from cmdline without changing zforth.c _( only TICK and COL words can change input_state to ZF_INPUT_PASS_WORD )_.
So you need to pass XT of the word for decompilation to stack and then run see.
e.g. `' words see`

**Comment by zevv** [comment]
merged, thanks!

**Pull request merged**
