### PR TITLE
new primitives - logical OR, XOR, bit rotations, speed up 3x by conditional trace() calls

### PR DESCRIPTION
**Pull request by martin-ac100**
added or ` | `, xor ` ^ `, bitshift left and right ` << ` and ` >> `
changed `trace(fmt, ... )` calls to `if(TRACE) trace(fmt, ...)`
this brings interpreter speed gain up to 3x

### CODE REVIEW

**Comment by zevv** [comment]
I'm happy with the new ops, but not too fond of the noise introduced by the `if(TRACE)` everywhere. I honestly wonder why the compiler is not smart enough to fix this for us, as an alternative we could make sure the function is inlined or otherwise provide a macro that hires the `if()`

Could you split the MR so that the new ops are in a separate commit? I'd like to spend some time to profile the tracing to see if we can get the speed gains without the noisy code.

Thanks!

**Comment by martin-ac100** [comment]
I see. First I tried to introduce new macro `TR(fmt, ...) if(TRACE) trace(fmt, __VA_ARGS__)` but this does not work for **-c89 standard**. It's defined in **-c99**. So that's why all these `if(TRACE)` exist.

**Comment by zevv** [comment]
I usually trust my compiler to do The Right Thing, and expected trace() to be inlined - interestingly, even if I explicitly `inline` it, I get no performance gains; my guess is that the varargs are making this hard for the compiler.

I'd gladly drop the c89 in favor of this huge performance boost, lets drop the c89 requirement and introduce a macro for tracing!

**Comment by zevv** [comment]
much nicer, right? 

Why the changes to `dict_put_cell()`, did you measure that to be faster than the normal functions? Also, please don't leave in commented-out code.

**Comment by martin-ac100** [comment]
I agree, nicer. This is tradeoff for -c89 -ansi leaving
regarding `dict_put_cell()` and `dict_get_cell()` macros. I did not notice any speed improvement, maybe compiler optimizes the unnecessary calls `dict_get_cell() -> return dict_get_cell_typed()`. It gives sense only for someone using non-optimizing compiler. Throw it away if I wish.
Sorry for my git processing errors. I am just rookie in using git. This is my first git experience. I am orthopaedic surgeon not an IT specialist.

**Comment by zevv** [comment]
> Sorry for my git processing errors. I am just rookie in using git.
> This is my first git experience. I am orthopaedic surgeon not an IT
> specialist.

Well, to be fair, I think you're likely to be better at Git than I am at
ortopaedic surgery :)

**Comment by zevv** [comment]
I just verified that gcc is indeed failing to inline the `trace()` function due to the varargs - my assumption was always that `trace()` was almost zero cost and collapsed down to a single branch, but indeed there's a full function being done.

https://gcc.gnu.org/bugzilla//show_bug.cgi?id=10980

I'm pulling in your macro change, thanks for noticing the speedup!

**Comment by zevv** [comment]
Hey @martin-ac100: I just pushed two commits implementing your PR, but slightly changed:
- shift left and shift right are called `SHL` and `SHR` instead of `RL` and `RR`
- I just implemented `trace()` as a macro and renamed the original trace to `do_trace()` - the resulting patch is a much smaller change because none of the other code is touched.

**Pull request closed without merging**
